replicaCount: 1

image:
  repository: ghcr.io/umario-chi/ai-customer-support-platform/ai-platform
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: a0060f42b778f4bccbdf5b8d1c63f432-2d8315f55cc0fc86.elb.eu-north-1.amazonaws.com

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: APP_ENV
    value: "production"
  - name: APP_LOG_LEVEL
    value: "warning"
  - name: LLM_BASE_URL
    value: "https://api.groq.com/openai/v1"
  - name: LLM_MODEL
    value: "llama-3.3-70b-versatile"
  - name: QDRANT_COLLECTION
    value: "faq_documents"
  - name: CACHE_TTL_SECONDS
    value: "3600"
